# feature_extraction.py

import logging
import numpy as np
import torch
from torch import nn
from typing import Dict, List, Tuple
from scipy.signal import savgol_filter
from scipy.ndimage import gaussian_filter1d
from scipy.stats import gaussian_kde
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest, mutual_info_classif
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.utils.class_weight import compute_class_weight
from sklearn.utils import shuffle
from sklearn.exceptions import NotFittedError
from sklearn.utils.validation import check_is_fitted
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.utils import check_array
from sklearn.utils.validation import check_is_fitted
from sklearn.utils.validation import check_X_y
from sklearn.utils.validation import check_consistent_length
from sklearn.utils.validation import column_or_1d
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import _check_X_y
from sklearn.utils.validation import _check_array
from sklearn.utils.validation import _check_sample_weight
from sklearn.utils.validation import _num_samples
from sklearn.utils.validation import