import logging
import os
import sys
import time
import numpy as np
import torch
from typing import Dict, List, Tuple
from scipy import stats
from scipy.spatial import distance
from scipy.stats import norm
from scipy.integrate import quad
from scipy.optimize import minimize
from scipy.special import erf
from scipy.stats import norm
from scipy.stats import uniform
from scipy.stats import expon
from scipy.stats import beta
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import nbinom
from scipy.stats import geom
from scipy.stats import hypergeom
from scipy.stats import chisquare
from scipy.stats import ttest_ind
from scipy.stats import ttest_rel
from scipy.stats import kstest
from scipy.stats import ks_2samp
from scipy.stats import normtest
from scipy.stats import anderson
from scipy.stats import kruskal
from scipy.stats import mannwhitneyu
from scipy.stats import rankdata
from scipy.stats import percentileofscore
from scipy.stats import mode
from scipy.stats import trim_mean
from scipy.stats import gmean
from scipy.stats import hmean
from scipy.stats import linregress
from scipy.stats import pearsonr
from scipy.stats import spearmanr
from scipy.stats import pointbiserialr
from scipy.stats import kendalltau
from scipy.stats import mstats
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean
from scipy.stats import circstd